version: '3.9'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  api:
    build: .
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://app:app@db:5432/app
      REDIS_URL: redis://redis:6379
      JWT_SECRET: devsecret
      ACCESS_TOKEN_EXPIRES: 15m
      REFRESH_TOKEN_EXPIRES: 7d
      REPO_DRIVER: prisma
      NODE_ENV: development
    ports:
      - "3000:3000"
volumes:
  db_data:
