version: '3.9'

services:
  frontend:
    build:
      context: ../../frontend
      dockerfile: ../deployment/docker/Dockerfile.frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ../../backend
      dockerfile: ../deployment/docker/Dockerfile.backend
    env_file:
      - ../config/.env
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
